In [1]:
import pandas

In [2]:
merged_dataframe = pandas.read_csv("merged_stocks_and_twitter_sentiment.csv")

In [3]:
merged_dataframe

Date       Open       High        Low      Close  Adj Close  \
0    2016-01-04  25.652500  26.342501  25.500000  26.337500  24.364536   
1    2016-01-05  26.437500  26.462500  25.602501  25.677500  23.753977   
2    2016-01-06  25.139999  25.592501  24.967501  25.174999  23.289116   
3    2016-01-07  24.670000  25.032499  24.107500  24.112499  22.306208   
4    2016-01-08  24.637501  24.777500  24.190001  24.240000  22.424154   
..          ...        ...        ...        ...        ...        ...   
916  2019-08-23  52.357498  53.012501  50.250000  50.660000  50.001186   
917  2019-08-26  51.465000  51.797501  51.264999  51.622501  50.951172   
918  2019-08-27  51.965000  52.137501  50.882500  51.040001  50.376244   
919  2019-08-28  51.025002  51.430000  50.830002  51.382500  50.714291   
920  2019-08-29  52.125000  52.330002  51.665001  52.252499  51.572975   

        Volume  ts_polarity  twitter_volume  
0    270597600     0.070389            1133  
1    223164000     0.133635            1430  
2    273829600     0.072042            1949  
3    324377600     0.074369            2289  
4    283192000     0.051595            2235  
..         ...          ...             ...  
916  187272000     0.097330            1103  
917  104174400     0.072340             888  
918  103493200     0.117541             962  
919   63755200     0.061477             895  
920   83962000     0.056460            1083  

[921 rows x 9 columns]

In [4]:
dataframe = merged_dataframe[["Date",
                             "Adj Close",
                             "Volume",
                             "ts_polarity",
                             "twitter_volume"]]

In [5]:
dataframe.set_index("Date", inplace = True)

In [6]:
dataframe

Adj Close     Volume  ts_polarity  twitter_volume
Date                                                         
2016-01-04  24.364536  270597600     0.070389            1133
2016-01-05  23.753977  223164000     0.133635            1430
2016-01-06  23.289116  273829600     0.072042            1949
2016-01-07  22.306208  324377600     0.074369            2289
2016-01-08  22.424154  283192000     0.051595            2235
...               ...        ...          ...             ...
2019-08-23  50.001186  187272000     0.097330            1103
2019-08-26  50.951172  104174400     0.072340             888
2019-08-27  50.376244  103493200     0.117541             962
2019-08-28  50.714291   63755200     0.061477             895
2019-08-29  51.572975   83962000     0.056460            1083

[921 rows x 4 columns]

In [7]:
sentiments = []

In [8]:
POSITIVE_SENTIMENT_THRESHOLD = 0.05

In [9]:
NEGATIVE_SENTIMENT_THRESHOLD = -0.05

In [10]:
for score in dataframe["ts_polarity"]:
    if score >= POSITIVE_SENTIMENT_THRESHOLD:
        sentiments.append("Positive")
    elif score <= NEGATIVE_SENTIMENT_THRESHOLD:
        sentiments.append("Negative")
    else :
        sentiments.append("Neutral")

In [11]:
dataframe["Sentiment"] = sentiments

C:\Users\ahUja\AppData\Local\Temp\ipykernel_11124\457913744.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe["Sentiment"] = sentiments


In [12]:
dataframe

Adj Close     Volume  ts_polarity  twitter_volume Sentiment
Date                                                                   
2016-01-04  24.364536  270597600     0.070389            1133  Positive
2016-01-05  23.753977  223164000     0.133635            1430  Positive
2016-01-06  23.289116  273829600     0.072042            1949  Positive
2016-01-07  22.306208  324377600     0.074369            2289  Positive
2016-01-08  22.424154  283192000     0.051595            2235  Positive
...               ...        ...          ...             ...       ...
2019-08-23  50.001186  187272000     0.097330            1103  Positive
2019-08-26  50.951172  104174400     0.072340             888  Positive
2019-08-27  50.376244  103493200     0.117541             962  Positive
2019-08-28  50.714291   63755200     0.061477             895  Positive
2019-08-29  51.572975   83962000     0.056460            1083  Positive

[921 rows x 5 columns]

In [13]:
dataframe["Sentiment"].value_counts()

Positive    784
Neutral     134
Negative      3
Name: Sentiment, dtype: int64

In [14]:
dataframe["Price Difference"] = dataframe["Adj Close"].diff()
dataframe.dropna(inplace =True)
dataframe

C:\Users\ahUja\AppData\Local\Temp\ipykernel_11124\1456260529.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe["Price Difference"] = dataframe["Adj Close"].diff()
C:\Users\ahUja\AppData\Local\Temp\ipykernel_11124\1456260529.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe.dropna(inplace =True)


Adj Close     Volume  ts_polarity  twitter_volume Sentiment  \
Date                                                                      
2016-01-05  23.753977  223164000     0.133635            1430  Positive   
2016-01-06  23.289116  273829600     0.072042            1949  Positive   
2016-01-07  22.306208  324377600     0.074369            2289  Positive   
2016-01-08  22.424154  283192000     0.051595            2235  Positive   
2016-01-11  22.787258  198957600     0.019443            1222   Neutral   
...               ...        ...          ...             ...       ...   
2019-08-23  50.001186  187272000     0.097330            1103  Positive   
2019-08-26  50.951172  104174400     0.072340             888  Positive   
2019-08-27  50.376244  103493200     0.117541             962  Positive   
2019-08-28  50.714291   63755200     0.061477             895  Positive   
2019-08-29  51.572975   83962000     0.056460            1083  Positive   

            Price Difference  
Date                          
2016-01-05         -0.610559  
2016-01-06         -0.464861  
2016-01-07         -0.982908  
2016-01-08          0.117946  
2016-01-11          0.363104  
...                      ...  
2019-08-23         -2.423077  
2019-08-26          0.949986  
2019-08-27         -0.574928  
2019-08-28          0.338047  
2019-08-29          0.858684  

[920 rows x 6 columns]

In [15]:
import numpy

In [16]:
RISE = 1
FALL = 0
dataframe ["Stock Trend"] = numpy.where(
    dataframe["Price Difference"]> 0, RISE, FALL)
dataframe

C:\Users\ahUja\AppData\Local\Temp\ipykernel_11124\993745085.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe ["Stock Trend"] = numpy.where(


Adj Close     Volume  ts_polarity  twitter_volume Sentiment  \
Date                                                                      
2016-01-05  23.753977  223164000     0.133635            1430  Positive   
2016-01-06  23.289116  273829600     0.072042            1949  Positive   
2016-01-07  22.306208  324377600     0.074369            2289  Positive   
2016-01-08  22.424154  283192000     0.051595            2235  Positive   
2016-01-11  22.787258  198957600     0.019443            1222   Neutral   
...               ...        ...          ...             ...       ...   
2019-08-23  50.001186  187272000     0.097330            1103  Positive   
2019-08-26  50.951172  104174400     0.072340             888  Positive   
2019-08-27  50.376244  103493200     0.117541             962  Positive   
2019-08-28  50.714291   63755200     0.061477             895  Positive   
2019-08-29  51.572975   83962000     0.056460            1083  Positive   

            Price Difference  Stock Trend  
Date                                       
2016-01-05         -0.610559            0  
2016-01-06         -0.464861            0  
2016-01-07         -0.982908            0  
2016-01-08          0.117946            1  
2016-01-11          0.363104            1  
...                      ...          ...  
2019-08-23         -2.423077            0  
2019-08-26          0.949986            1  
2019-08-27         -0.574928            0  
2019-08-28          0.338047            1  
2019-08-29          0.858684            1  

[920 rows x 7 columns]

In [17]:
new_dataframe = dataframe [["Adj Close",
                           "Volume",
                           "twitter_volume",
                          "Sentiment",
                          "Stock Trend"]]

In [18]:
new_dataframe = pandas.get_dummies(new_dataframe, columns = ["Sentiment"])

In [19]:
new_dataframe

Adj Close     Volume  twitter_volume  Stock Trend  \
Date                                                            
2016-01-05  23.753977  223164000            1430            0   
2016-01-06  23.289116  273829600            1949            0   
2016-01-07  22.306208  324377600            2289            0   
2016-01-08  22.424154  283192000            2235            1   
2016-01-11  22.787258  198957600            1222            1   
...               ...        ...             ...          ...   
2019-08-23  50.001186  187272000            1103            0   
2019-08-26  50.951172  104174400             888            1   
2019-08-27  50.376244  103493200             962            0   
2019-08-28  50.714291   63755200             895            1   
2019-08-29  51.572975   83962000            1083            1   

            Sentiment_Negative  Sentiment_Neutral  Sentiment_Positive  
Date                                                                   
2016-01-05                   0                  0                   1  
2016-01-06                   0                  0                   1  
2016-01-07                   0                  0                   1  
2016-01-08                   0                  0                   1  
2016-01-11                   0                  1                   0  
...                        ...                ...                 ...  
2019-08-23                   0                  0                   1  
2019-08-26                   0                  0                   1  
2019-08-27                   0                  0                   1  
2019-08-28                   0                  0                   1  
2019-08-29                   0                  0                   1  

[920 rows x 7 columns]

In [20]:
x = new_dataframe.copy()
x.drop("Stock Trend", axis=1 , inplace=True)
x

Adj Close     Volume  twitter_volume  Sentiment_Negative  \
Date                                                                   
2016-01-05  23.753977  223164000            1430                   0   
2016-01-06  23.289116  273829600            1949                   0   
2016-01-07  22.306208  324377600            2289                   0   
2016-01-08  22.424154  283192000            2235                   0   
2016-01-11  22.787258  198957600            1222                   0   
...               ...        ...             ...                 ...   
2019-08-23  50.001186  187272000            1103                   0   
2019-08-26  50.951172  104174400             888                   0   
2019-08-27  50.376244  103493200             962                   0   
2019-08-28  50.714291   63755200             895                   0   
2019-08-29  51.572975   83962000            1083                   0   

            Sentiment_Neutral  Sentiment_Positive  
Date                                               
2016-01-05                  0                   1  
2016-01-06                  0                   1  
2016-01-07                  0                   1  
2016-01-08                  0                   1  
2016-01-11                  1                   0  
...                       ...                 ...  
2019-08-23                  0                   1  
2019-08-26                  0                   1  
2019-08-27                  0                   1  
2019-08-28                  0                   1  
2019-08-29                  0                   1  

[920 rows x 6 columns]

In [21]:
y = new_dataframe["Stock Trend"].values.reshape(-1,1)
y[:10]


array([[0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0]])

In [22]:
SPLIT = int (0.8*len(x))
x_train = x[:SPLIT]

x_test = x[SPLIT:]

y_train = y[:SPLIT]
y_test = y[SPLIT:]

In [24]:
y_test

array([[0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [24]:
x_test

Adj Close     Volume  twitter_volume  Sentiment_Negative  \
Date                                                                   
2018-12-06  42.601311  172393600            1131                   0   
2018-12-07  41.082272  169126400            1169                   0   
2018-12-10  41.352917  248104000            1553                   0   
2018-12-11  41.116405  189126800            1494                   0   
2018-12-12  41.231007  142510800            1119                   0   
...               ...        ...             ...                 ...   
2019-08-23  50.001186  187272000            1103                   0   
2019-08-26  50.951172  104174400             888                   0   
2019-08-27  50.376244  103493200             962                   0   
2019-08-28  50.714291   63755200             895                   0   
2019-08-29  51.572975   83962000            1083                   0   

            Sentiment_Neutral  Sentiment_Positive  
Date                                               
2018-12-06                  0                   1  
2018-12-07                  0                   1  
2018-12-10                  0                   1  
2018-12-11                  0                   1  
2018-12-12                  0                   1  
...                       ...                 ...  
2019-08-23                  0                   1  
2019-08-26                  0                   1  
2019-08-27                  0                   1  
2019-08-28                  0                   1  
2019-08-29                  0                   1  

[184 rows x 6 columns]

In [30]:
from sklearn.preprocessing import StandardScaler

In [31]:
scaler = StandardScaler()

x_scaler = scaler.fit(x_train)
x_train_scaled = x_scaler.transform(x_train)
x_test_scaled = x_scaler.transform(x_test)

x_train_scaled

array([[-1.20713384,  1.53043007,  0.37552719, -0.06397476, -0.46532669,
         0.47179589],
       [-1.2557263 ,  2.37394   ,  1.06913333, -0.06397476, -0.46532669,
         0.47179589],
       [-1.3584708 ,  3.21549206,  1.52351885, -0.06397476, -0.46532669,
         0.47179589],
       ...,
       [ 0.86138119,  0.44764019, -1.11726289, -0.06397476, -0.46532669,
         0.47179589],
       [ 1.0204222 ,  0.53228153, -0.35148964, -0.06397476, -0.46532669,
         0.47179589],
       [ 0.81320968,  0.56836232,  0.30068722, -0.06397476, -0.46532669,
         0.47179589]])

In [32]:
from sklearn.ensemble import RandomForestClassifier
NUMBER_OF_ESTIMATORS = 500
RANDOM_STATE = 80

classifier = RandomForestClassifier(n_estimators= NUMBER_OF_ESTIMATORS,
                                   random_state=RANDOM_STATE)



In [33]:
x_test_scaled

array([[ 0.76299971,  0.68517536, -0.02406478, -0.06397476, -0.46532669,
         0.47179589],
       [ 0.60421281,  0.63078115,  0.02671948, -0.06397476, -0.46532669,
         0.47179589],
       [ 0.63250364,  1.94564547,  0.53990784, -0.06397476, -0.46532669,
         0.47179589],
       ...,
       [ 1.57572242, -0.46191797, -0.24992112, -0.06397476, -0.46532669,
         0.47179589],
       [ 1.61105886, -1.12349895, -0.33946179, -0.06397476, -0.46532669,
         0.47179589],
       [ 1.70081809, -0.78708457, -0.08821333, -0.06397476, -0.46532669,
         0.47179589]])

In [34]:
y_train

array([[0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
    

In [35]:
y_train.ravel()

array([0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,

In [36]:
classifier = classifier.fit(x_train_scaled,y_train.ravel())



In [37]:
classifier.warm_start

False

In [38]:
predictions = classifier.predict(x_test_scaled)

In [39]:
predictions

array([1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1])

In [40]:
pandas.DataFrame({
    "Predictions": predictions,
    "Actual": y_test.ravel()
})

Predictions  Actual
0              1       0
1              0       0
2              0       1
3              0       0
4              1       1
..           ...     ...
179            0       0
180            1       1
181            0       0
182            1       1
183            1       1

[184 rows x 2 columns]

In [41]:
from sklearn.metrics import accuracy_score

In [42]:
accuracy = accuracy_score(y_test, predictions)
print(accuracy)

0.5434782608695652


In [43]:
from sklearn.metrics import classification_report

In [44]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.49      0.44      0.46        82
           1       0.58      0.63      0.60       102

    accuracy                           0.54       184
   macro avg       0.53      0.53      0.53       184
weighted avg       0.54      0.54      0.54       184



In [45]:
from sklearn.metrics import confusion_matrix

In [46]:
confusion_matrix_results = confusion_matrix(y_test, predictions)
confusion_matrix_dataframe = pandas.DataFrame(confusion_matrix_results,
                index = ["Actual 0", "Actual 1"],
                columns= ["Predicted 0",  "Predicted 1"])

display(confusion_matrix_dataframe)

Predicted 0  Predicted 1
Actual 0           36           46
Actual 1           38           64

In [47]:
from sklearn.ensemble import GradientBoostingClassifier


NUMBER_OF_ESTIMATORS = 30
MAX_NUMBER_OF_FEATURES = 2
MAX_DEPTH=3
RANDOOM_STATE_CONSTANT =0

learning_rates = [0.05,0.1,0.25,0.5,0.75,1,1.5,2]

for learning_rate in learning_rates:
    classifier = GradientBoostingClassifier(n_estimators= NUMBER_OF_ESTIMATORS,
                                           learning_rate= learning_rate,
                                           max_features= MAX_NUMBER_OF_FEATURES,
                                           max_depth=MAX_DEPTH,
                                           random_state=RANDOOM_STATE_CONSTANT)
    
    classifier.fit(x_train_scaled, y_train.ravel())
    
    training_score = classifier.score(x_train_scaled,y_train.ravel())
    testing_score = classifier.score(x_test_scaled,y_test.ravel())
    
    print("Learning rate: ", learning_rate)
    print("Training Accuracy: ", training_score)
    print("Testing Accuracy: ", testing_score)
    print()
    
    
    
 

Learning rate:  0.05
Training Accuracy:  0.6413043478260869
Testing Accuracy:  0.6304347826086957

Learning rate:  0.1
Training Accuracy:  0.6725543478260869
Testing Accuracy:  0.625

Learning rate:  0.25
Training Accuracy:  0.71875
Testing Accuracy:  0.6086956521739131

Learning rate:  0.5
Training Accuracy:  0.7635869565217391
Testing Accuracy:  0.5652173913043478

Learning rate:  0.75
Training Accuracy:  0.782608695652174
Testing Accuracy:  0.5217391304347826

Learning rate:  1
Training Accuracy:  0.8274456521739131
Testing Accuracy:  0.5271739130434783

Learning rate:  1.5
Training Accuracy:  0.8383152173913043
Testing Accuracy:  0.5271739130434783

Learning rate:  2
Training Accuracy:  0.47146739130434784
Testing Accuracy:  0.44021739130434784



In [48]:
LEARNING_RATE = 1

MAX_NUMBER_OF_FEATURES = 5


classifier = GradientBoostingClassifier(n_estimators= NUMBER_OF_ESTIMATORS,
                                      learning_rate=LEARNING_RATE,
                                      max_features=MAX_NUMBER_OF_FEATURES,
                                      max_depth=MAX_DEPTH,
                                      random_state=RANDOOM_STATE_CONSTANT
                                      )

classifier.fit(x_train_scaled, y_train.ravel())

training_score = classifier.score(x_train_scaled,y_train.ravel())
testing_score = classifier.score(x_test_scaled,y_test.ravel())

print("Learning rate: ", LEARNING_RATE)
print("Training Accuracyy: ", training_score)
print("Testing Accuracy: ", testing_score)
print()


Learning rate:  1
Training Accuracyy:  0.875
Testing Accuracy:  0.5815217391304348



In [56]:
predictions = classifier.predict(x_test_scaled)
pandas.DataFrame({
    "Prediction": predictions,
    "Actual Stock Trend": y_test.ravel()
    
})

Prediction  Actual Stock Trend
0             1                   0
1             0                   0
2             0                   1
3             0                   0
4             0                   1
..          ...                 ...
179           0                   0
180           1                   1
181           1                   0
182           1                   1
183           1                   1

[184 rows x 2 columns]

In [57]:
accuracy = accuracy_score(y_test, predictions)
print("Prediction Model Accuracy: ", accuracy)

Prediction Model Accuracy:  0.5815217391304348


In [58]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.53      0.52      0.53        82
           1       0.62      0.63      0.62       102

    accuracy                           0.58       184
   macro avg       0.58      0.58      0.58       184
weighted avg       0.58      0.58      0.58       184



In [59]:
confusion_matrix_results = confusion_matrix(y_test,predictions)

confusion_matrix_dataframe = pandas.DataFrame(confusion_matrix_results,
                index = ["Actual 0", "Actual 1"],
                columns=["Predicted 0", "Predicted 1"])

print(confusion_matrix_dataframe)

          Predicted 0  Predicted 1
Actual 0           43           39
Actual 1           38           64
